default: &default
  adapter: mysql2
  encoding: utf8
  host: euler-development.cuf8ndvbjwtn.us-east-1.rds.amazonaws.com
  port: 3306
  username: root
  password: ruicosta84

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'euler_development' %>

test:
  <<: *default
  database: euler_test

production:
  <<: *default
  database: euler
  url: <%= ENV['DATABASE_URL'] %>
