default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'euler_development' %>

test:
  <<: *default
  database: euler_test

production:
  <<: *default
  database: euler
